# Generated by Django 4.0.3 on 2022-03-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Coin')),
                ('ticker', models.CharField(max_length=100, verbose_name='Ticker')),
            ],
            options={
                'db_table': 'coin',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_symbol', models.CharField(max_length=100, verbose_name='Exchange symbol')),
                ('display_symbol', models.CharField(max_length=100, verbose_name='Display symbol')),
                ('exchange_name', models.CharField(max_length=200, verbose_name='Exchange name')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='Coins_exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=100)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin')),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exchange')),
            ],
            options={
                'db_table': 'coin_exchange',
            },
        ),
    ]
